default: &default
  adapter: postgresql
  timeout: 5000
  user: elenok

development:
  <<: *default
  database: blog
  url: postgresql://localhost/blog?pool=5

test:
  <<: *default
  database: blog_test
  url: postgresql://localhost/blog_test?pool=5

production:
  <<: *default
  database: blog
